export const SET_STEP_SIGNUP = "SET_STEP_SIGNUP"; 
export const SET_SHOW_CONFIRM_MAP = "SET_SHOW_CONFIRM_MAP";
export const SET_REGION = "SET_REGION";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_SEARCH_REGION = "SET_SEARCH_REGION";
export const SET_CREATING_ACCOUNT = "SET_CREATING_ACCOUNT";
